/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyExpensesRouteImport } from './routes/my-expenses'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TimeRouteImport } from './routes/time'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as ExpensesExpenseIdRouteImport } from './routes/expenses.$expenseId'
import { Route as ExpensesNewRouteImport } from './routes/expenses.new'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamUserIdRouteImport } from './routes/team.$userId'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiReceiptsExpenseIdRouteImport } from './routes/api/receipts/$expenseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyExpensesRoute = MyExpensesRouteImport.update({
  id: '/my-expenses',
  path: '/my-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesExpenseIdRoute = ExpensesExpenseIdRouteImport.update({
  id: '/expenses/$expenseId',
  path: '/expenses/$expenseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesNewRoute = ExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamUserIdRoute = TeamUserIdRouteImport.update({
  id: '/team/$userId',
  path: '/team/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptsExpenseIdRoute = ApiReceiptsExpenseIdRouteImport.update({
  id: '/api/receipts/$expenseId',
  path: '/api/receipts/$expenseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-expenses': typeof MyExpensesRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/time': typeof TimeRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/team/$userId': typeof TeamUserIdRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/team/': typeof TeamIndexRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/receipts/$expenseId': typeof ApiReceiptsExpenseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-expenses': typeof MyExpensesRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/time': typeof TimeRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/team/$userId': typeof TeamUserIdRoute
  '/expenses': typeof ExpensesIndexRoute
  '/team': typeof TeamIndexRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/receipts/$expenseId': typeof ApiReceiptsExpenseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-expenses': typeof MyExpensesRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/time': typeof TimeRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/team/$userId': typeof TeamUserIdRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/team/': typeof TeamIndexRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/receipts/$expenseId': typeof ApiReceiptsExpenseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-expenses'
    | '/reports'
    | '/signup'
    | '/time'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/invite/$token'
    | '/team/$userId'
    | '/expenses/'
    | '/team/'
    | '/api/auth/signout'
    | '/api/receipts/$expenseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-expenses'
    | '/reports'
    | '/signup'
    | '/time'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/invite/$token'
    | '/team/$userId'
    | '/expenses'
    | '/team'
    | '/api/auth/signout'
    | '/api/receipts/$expenseId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-expenses'
    | '/reports'
    | '/signup'
    | '/time'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/invite/$token'
    | '/team/$userId'
    | '/expenses/'
    | '/team/'
    | '/api/auth/signout'
    | '/api/receipts/$expenseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyExpensesRoute: typeof MyExpensesRoute
  ReportsRoute: typeof ReportsRoute
  SignupRoute: typeof SignupRoute
  TimeRoute: typeof TimeRoute
  ExpensesExpenseIdRoute: typeof ExpensesExpenseIdRoute
  ExpensesNewRoute: typeof ExpensesNewRoute
  InviteTokenRoute: typeof InviteTokenRoute
  TeamUserIdRoute: typeof TeamUserIdRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiReceiptsExpenseIdRoute: typeof ApiReceiptsExpenseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-expenses': {
      id: '/my-expenses'
      path: '/my-expenses'
      fullPath: '/my-expenses'
      preLoaderRoute: typeof MyExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/$expenseId': {
      id: '/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof ExpensesExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/new': {
      id: '/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$userId': {
      id: '/team/$userId'
      path: '/team/$userId'
      fullPath: '/team/$userId'
      preLoaderRoute: typeof TeamUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipts/$expenseId': {
      id: '/api/receipts/$expenseId'
      path: '/api/receipts/$expenseId'
      fullPath: '/api/receipts/$expenseId'
      preLoaderRoute: typeof ApiReceiptsExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyExpensesRoute: MyExpensesRoute,
  ReportsRoute: ReportsRoute,
  SignupRoute: SignupRoute,
  TimeRoute: TimeRoute,
  ExpensesExpenseIdRoute: ExpensesExpenseIdRoute,
  ExpensesNewRoute: ExpensesNewRoute,
  InviteTokenRoute: InviteTokenRoute,
  TeamUserIdRoute: TeamUserIdRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiReceiptsExpenseIdRoute: ApiReceiptsExpenseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
