/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyExpensesRouteImport } from './routes/my-expenses'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as ExpensesExpenseIdRouteImport } from './routes/expenses.$expenseId'
import { Route as ExpensesNewRouteImport } from './routes/expenses.new'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiReceiptsFileIdRouteImport } from './routes/api/receipts/$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyExpensesRoute = MyExpensesRouteImport.update({
  id: '/my-expenses',
  path: '/my-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesExpenseIdRoute = ExpensesExpenseIdRouteImport.update({
  id: '/expenses/$expenseId',
  path: '/expenses/$expenseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesNewRoute = ExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptsFileIdRoute = ApiReceiptsFileIdRouteImport.update({
  id: '/api/receipts/$fileId',
  path: '/api/receipts/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-expenses': typeof MyExpensesRoute
  '/reports': typeof ReportsRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/receipts/$fileId': typeof ApiReceiptsFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-expenses': typeof MyExpensesRoute
  '/reports': typeof ReportsRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses': typeof ExpensesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/receipts/$fileId': typeof ApiReceiptsFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-expenses': typeof MyExpensesRoute
  '/reports': typeof ReportsRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/receipts/$fileId': typeof ApiReceiptsFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-expenses'
    | '/reports'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/expenses/'
    | '/api/auth/google'
    | '/api/auth/signout'
    | '/api/receipts/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-expenses'
    | '/reports'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/expenses'
    | '/api/auth/google'
    | '/api/auth/signout'
    | '/api/receipts/$fileId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-expenses'
    | '/reports'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/expenses/'
    | '/api/auth/google'
    | '/api/auth/signout'
    | '/api/receipts/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyExpensesRoute: typeof MyExpensesRoute
  ReportsRoute: typeof ReportsRoute
  ExpensesExpenseIdRoute: typeof ExpensesExpenseIdRoute
  ExpensesNewRoute: typeof ExpensesNewRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiReceiptsFileIdRoute: typeof ApiReceiptsFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-expenses': {
      id: '/my-expenses'
      path: '/my-expenses'
      fullPath: '/my-expenses'
      preLoaderRoute: typeof MyExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/$expenseId': {
      id: '/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof ExpensesExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/new': {
      id: '/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipts/$fileId': {
      id: '/api/receipts/$fileId'
      path: '/api/receipts/$fileId'
      fullPath: '/api/receipts/$fileId'
      preLoaderRoute: typeof ApiReceiptsFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyExpensesRoute: MyExpensesRoute,
  ReportsRoute: ReportsRoute,
  ExpensesExpenseIdRoute: ExpensesExpenseIdRoute,
  ExpensesNewRoute: ExpensesNewRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiReceiptsFileIdRoute: ApiReceiptsFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
